name    'ft-brands_rw_neo4j'
version '0.0.0'
source 'git@github.com:Financial-Times/brands-rw-neo4j.git'
author 'ft'
license 'Apache License, Version 2.0'
summary ''
description 'Go RWD micro service'
project_page 'https://github.com/Financial-Times/brands-rw-neo4j'

## Add dependencies, if any:
dependency 'ft/go_service_profile', '>= 0.0.0'
